#!/usr/bin/env bash
# the script transfers a file from our client to a server
ARGS=4
ERR_ARGS=1
if [ "$#" -ne "$ARGS" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit "$ERR_ARGS"
fi
# Disable Strict host key checking
scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3"@"$2":~\
