#!/usr/bin/env bash
# this script using ping command to diagnosis and measurement
# the host network status 5 times
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
ARGS=1
E_BADARGS=85
if [ $# -ne "$ARGS" ]
then
	echo "Usage: $(basename $0) {IP_ADDRESS}"
	exit $E_BADARGS
fi
ping -c 5 $1