#!/usr/bin/env bash
#-------
# a shell script displays text string 10 times
#-------
hour=0
while [ "$hour" -ne 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ "$minute" -ne 60 ]
    do
	echo "$minute"
	minute=$((minute+1))
    done
    hour=$((hour+1))
done
