#!/usr/bin/env bash
#-------
# a shell script displays text string 10 times
#-------
file="holbertonschool"
filename="./holbertonschool"
if [ -e "$filename" ]
then
    echo "$file file is exists"
    if [ -s "$filename" ]
    then
	echo "$file file is not empty"
    else
	echo "$file file is empty"
    fi

    if [ -f "$filename" ]
    then
	echo "$file is a regular file"
    fi
else
    echo "$file file does not exist"
fi
