#!/usr/bin/env bash
# the script stops apache2 and start nginx as web service under user nginx
chmod o+wr /etc/nginx/nginx.conf
sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default
sed -i "s/listen \[::\]:80/listen [::]:8080/" /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
